services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
  jenkins:
    privileged: true
    build: .
    restart: always
    ports:
        - "8080:8080"
    volumes:
        - './jenkins_home:/var/jenkins_home'
        - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
        TZ: "Asia/Seoul"
